--- 
url: https://www.sacconnects.net
timezone: America/New_York
future: true
markdown: kramdown
kramdown:
  auto_ids: false
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gruntfile.js
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
collections:
  pages: 
    output: true
  redirects:
    output: true
  clients:
    output: true      
defaults:
- scope:
    type: 'pages'
  values:
    layout: basic-page
- scope:
    type: 'redirects'
  values:
    layout: redirect
- scope: 
    type: 'clients'
  values:
    sitemap: false      

