title: SacConnects
description: Your destination for premium business connections, recruitment of
  board members, and board effectiveness and engagement guidance.
meta_img: /assets/images/sc-meta.png
favicon: /assets/images/sacconnects-favicon1.png
gtm: GTM-K5SM2XG
schema:
  logo: assets/images/sacconnects-logo.png
  name: SacConnects
  social: null
  phone: null
  
  type: Organization
  image: null
  email: nancy@sacconnects.net
