title: SacConnects
description: Your destination for premium board and association recruitment and board effectiveness guidance.
meta_img: 
favicon:
gtm: GTM-K5SM2XG
schema:
  name: SacConnects
  type: Organization
  image: 
  logo: assets/images/sacconnects-logo.png
  phone: 
  email: nancy@sacconnects.net
  social: 
  location: 
    address: 
    city: 
    state: 
    zip: 
  hours:
    days: 
    opens:
    closes: 