backend:
  name: git-gateway
  branch: main 
local_backend:
  url: 'http://localhost:4000/api/v1'
media_folder: 'assets/images'
collections:
- name: 'clients'
  label: 'Clients'
  folder: '_clients/'
  publish_mode: editorial_workflow
  create: true
  editor:
    preview: false
  fields: 
    - label: 'Title'
      name: 'title'
      widget: 'string'
    - label: 'Logo'
      name: 'logo'
      widget: 'image'
      choose_url: false
      
      required: false
    - label: 'Website'
      name: site
      widget: 'string'
      required: false
    - label: 'Review'
      name: 'review'
      widget: 'object'
      required: false
      collapsed: true
      fields:
        - label: 'Review text'
          name: 'text'
          widget: 'markdown'
          required: false
        - label: 'Excerpt' 
          name: 'excerpt'
          required: false
          hint: 'Optional field if you want to use a select line of text instead of the first sentence of the review on the homepage.'
          widget: 'markdown'
        - label: 'source'
          name: 'review'
          widget: 'object'
          hint: 'Add a name, title, and organization for who gave the review. If none is specified, then it will default to the client title.'
          fields: 
            - label: 'Name'
              name: 'name'
              widget: 'string'
              required: false
            - label: 'Title'
              name: 'title'
              widget: 'string'   
              required: false 
            - label: 'Organization'
              name: 'org'
              widget: 'string'
              required: false
              hint: 'Alternate organization name for the client. If none is specified, then it will default to the client title.'
- name: 'pages'
  label: 'Pages'
  folder: '_pages/'
  create: true
  editor: 
    preview: true
  fields:
  - name: 'title'
    label: 'Title'
    widget: 'string'
  - name: 'body'
    label: 'Body'
    widget: 'markdown' 
  - name: 'permalink'
    label: 'Permalink'
    required: false
    hint: 'Optional since the link will automatically generate when you create it based on the title. Just specify the page path like so: /my-page-permalink/'                        
- name: 'home'
  label: 'Home Page'
  create: false
  editor:
    preview: false
  files:
    - label: 'Home Page'
      name: 'home'
      file: 'index.md'
      fields:
        - name: 'hero'
          label: 'Hero Section'
          hint: 'The section at the top of the page with the welcome message and the image slider'
          widget: 'object'
          collapsed: true
          fields:
          - name: 'title'
            label: 'Title'
            widget: 'string'
            hint: 'The title text at the top of the hero section'
          - name: 'text'
            label: 'Text'
            widget: 'text'
            hint: 'The text below the title of the hero section'
          - name: 'cta'
            label: 'Call to Action'
            widget: 'object'
            hint: 'The text link below the text of the hero section'
            fields: 
            - name: 'text'
              label: 'Text'
              widget: 'string'
            - name: 'link'
              label: 'Link'
              widget: 'string'
          - name: 'images'
            label: 'Image slider'
            hint: 'The image slider in the hero section. Add slides by clicking [button]'
            widget: 'list'
            collapsed: true
            fields: 
            - name: 'src'
              label: 'Image'
              widget: 'image'
              choose_url: false
            - name: 'alt'
              label: 'Image description (alt) text'
              hint: 'Description or alt text is a way to describe an image to screen readers for people with disabilities. This is required by the ADA and will help your search ranking.'
              widget: 'string'
            - name: 'text'
              label: 'Text'
              hint: 'The text that appears in the purple box in the bottom-right corner of the slide.'  
        - name: 'about'
          label: 'About Section'
          hint: 'The section below the hero where you talk about yourself.'
          widget: 'object'
          collapsed: true
          fields:
          - name: 'title'
            label: 'Title'
            hint: 'Title text of the about section'
            widget: 'string' 
          - name: 'text'
            label: 'Text'
            hint: 'Text for the about section'
            widget: 'text'
          - name: 'image'
            label: 'Image' 
            hint: 'Image for the about section. Alt text already configured as "headshot of Nancy Brodovsky".'  
          - name: 'cta'
            label: 'Call to Action'
            hint: 'Link text at the bottom of the about section'  
            widget: 'object'
            fields:
            - name: 'text'
              label: 'Text'
              hint: 'Link text. No need to add the arrows, they are automatically generated.'
              widget: 'string'
            - name: 'link'
              label: 'Link'
              hint: 'Link URL'
              widget: 'string'
        - name: 'news'
          label: 'News section'
          hint: "Add links to media you're featured in here"
          widget: 'object'
          collapsed: true
          fields: 
          - name: 'title'
            label: "Title"
            hint: 'The title text that appears at the top of the page'
            widget: 'string'
          - name: 'articles'
            label: 'Media'
            hint: 'Add a new link to media or edit existing links here'
            widget: 'list'
            fields: 
            - name: 'title'
              label: 'Title'
              widget: 'string'
              hint: 'Title of the media'
            - name: 'outlet'
              label: 'Outlet'
              hint: 'Press outlet of the media'
              widget: 'string'
            - name: 'link'
              label: 'Link'
              widget: 'string'
              hint: 'Link to the media. Link will be applied to the media title'       
        - name: 'reviews'
          label: 'Reviews section'
          hint: 'Add featured reviews from your clients here'
          widget: 'object'
          collapsed: true
          fields: 
          - name: 'title'
            label: 'Review section title'
            widget: 'string'
          - name: 'list'
            label: 'Reviews list'
            hint: 'Add or delete reviews here. Just select which client you want and order however you wish and the review excerpt or the first sentence of the review will appear on the homepage.'
            widget: 'list'
            fields:
            - name: 'client'
              label: 'Client'
              collection: 'clients'
              search_fields: ["title"]
              display_fields: ["title"]
              value_field: "{{slug}}"
              widget: 'relation'
        - name: 'clients'
          label: 'Clients section'
          hint: 'This section automatically feeds in all the clients you have added in alphabetical order. All you need to so here is update a title.'
          widget: 'object'
          collapsed: true
          fields:
          - name: 'title'
            label: 'Client section title'
            widget: 'string'
- name: 'nav'
  label: 'Navigation menu'
  hint: 'Add/edit links for navigation menu here.'                
  create: false
  editor:
    preview: false
  files: 
  - name: 'nav'
    label: 'Navigation'
    file: '_data/nav.yml'
    fields: 
      - name: 'logo'
        label: 'Logo'
        hint: 'The logo that appears on the left-hand side of the navigation menu'
        widget: image
        choose_url: false
        allow_multiple: false
      - name: 'links'
        label: 'Links'
        hint: 'Add,remove, or reorder links on the right-hand side of the navigation menu'
        widget: list
        collapsed: true
        fields: 
        - name: title
          label: 'Title'
          widget: 'string'
        - name: url
          label: 'Page link'
          hint: 'select the page you want to link to. If this is a submenu link, you can leave this field empty.'
          widget: 'relation'
          required: false
          collection: 'pages'
          search_fields: ['title']
          display_fields: ['title']
          value_field: '{{slug}}'
        - name: 'submenu'
          label: 'Submenu links'
          hint: 'These links will appear in a dropdown below the page link specified above'
          widget: list
          required: false
          fields: 
          - name: url
            label: 'Page link'
            hint: 'select the page you want to link to. Title will automatically be configured.'
            widget: 'relation'
            required: false
            collection: 'pages'
            search_fields: ['title']
            display_fields: ['title']
            value_field: '{{slug}}'
        - name: custom-link
          label: 'Custom link'
          hint: 'If you need to link to any outside sites, the link can be added here.'
          required: false
          widget: 'string'
- name: footer
  label: 'Footer'
  create: false
  editor:
    preview: false
  files: 
  - file: '_data/footer.yml'
    name: footer
    label: 'Footer'
    hint: 'The dark gray footer that appears on all pages'
    fields: 
    - name: copyright
      label: 'Copyright'
      widget: 'string'
      hint: 'Text to the right of the copyright symbol and year. Year is automatically generated from the current date.'
    - name: links
      label: 'Links'
      widget: 'list'
      hint: 'The links that appear from left to right at the bottom of the footer.'
      fields: 
      - name: title
        label: 'Link title'
        widget: 'string'
        hint: 'The title of the link that will appear.'
      - name: url
        label: 'Link URL'
        widget: 'string'
        hint: 'The link users will go to on click. Add both internal and external links here.'  
- name: 'meta'
  label: 'Site info'
  create: false
  editor: 
    preview: false
  files: 
  - file: '_data/meta.yml' 
    name: 'meta'
    label: 'Site info' 
    hint: 'All of your site information, ie Meta Data, will live here.'
    fields: 
    - name: 'title'
      label: 'Site Title'
      widget: 'string'
      hint: 'The title of your site you want social media and search engines to display'
    - name: 'description'
      label: 'Site description'
      hint: 'The description of your site you want social media and search engines to display'  
    - name: 'meta_img'
      label: 'Site image'
      widget: 'image'
      choose_url: false
      hint: 'The image for your site you want social media display when you share a link'  
    - name: 'favicon'  
      label: 'Site Favicon'
      widget: 'image'
      choose_url: false
      hint: 'The small image that appears on the browser tab for your website'
    - name: 'gtm'
      label: 'Google Tag Manager property'  
      widget: 'string'
      hint: 'The property ID for your Google Tag Manager container'
    - name: 'schema'
      label: 'Business Information'
      collapsed: true
      widget: 'object'
      required: false
      hint: 'Information about your business so Google can show it as rich results. None of these fields are required'
      fields:
      - name: 'name'
        label: 'Business Name' 
        widget: 'string'
        required: false
      - name: 'logo'
        label: 'Business logo'
        widget: 'image'
        choose_url: false
        hint: 'Your business logo'  
        required: false
      - name: 'image'
        label: 'Business Image'
        widget: 'image'
        choose_url: false
        hint: 'an image of your business like a curbside photo or interior shots'
        required: false
      - name: 'phone'
        label: 'Business phone'
        widget: 'string'
        required: false
      - name: 'email'
        label: 'Business email'
        widget: 'string'
        required: false
      - name: 'social'
        label: 'Social media profiles' 
        hint: 'Paste in your social media profiles here. Add a comma after each to add another profile'
        widget: 'list' 
        required: false
      - name: 'location'
        label: 'Business Location'
        widget: 'object'
        required: false
        fields:
        - name: 'address'
          label: 'Address'
          widget: 'string'
          required: false
        - name: 'city'
          label: 'City'
          widget: 'string'
          required: false
        - name: 'zip'
          label: 'Zip'
          widget: 'string'
          required: false
      - name: 'hours'
        label: 'Business Hours'    
        widget: 'object'
        fields: 
        - name: 'days'
          label: "Days"
          hint: 'Type in the days of the week you are operating with a comma after each'
          widget: 'list'
          required: false
        - name: 'opens'
          label: 'Opening time of your business'
          widget: 'string'
          required: false
        - name: 'closes'
          label: 'Closing time of your business'
          widget: 'string'
          required: false


                  
            
            

        


        



          

      

          
                
                  

                


               

        


              
              





        
