backend:
  name: git-gateway
  branch: main 
local_backend:
  url: http://localhost:4000/api/v1
media_folder: 'assets/images'
collections:
- name: 'clients'
  label: 'Clients'
  folder: '_clients/'
  create: true
  editor:
    preview: false
  fields: 
    - label: 'Title'
      name: 'title'
      required: true
      widget: 'string'
    - label: 'Logo'
      name: 'logo'
      widget: 'image'
    - label: 'Review'
      name: 'review'
      widget: 'object'
      collapsed: true
      fields:
        - label: 'Review text'
          name: 'text'
          widget: 'markdown'
        - label: 'Excerpt' 
          name: 'excerpt'
          hint: 'Optional field if you want to use a select line of text instead of the first sentence of the review on the homepage.'
          widget: 'markdown'
        - label: 'source'
          name: 'review'
          widget: 'object'
          hint: 'Add a name, title, and organization for who gave the review. If none is specified, then it will default to the client title.'
          fields: 
            - label: 'Name'
              name: 'name'
              widget: 'string'
            - label: 'Title'
              name: 'title'
              widget: 'string'    
            - label: 'Organization'
              name: 'org'
              widget: 'string'
              hint: 'Alternate organization name for the client. If none is specified, then it will default to the client title.'
- name: 'pages'
  label: 'Pages'
  folder: '_pages/'
  create: true
  editor: 
    preview: true
  fields:
  - name: 'title'
    label: 'Title'
    required: true
    widget: 'string'
  - name: 'body'
    label: 'Body'
    widget: 'markdown' 
  - name: 'permalink'
    label: 'Permalink'
    hint: 'Completely optional since the link will automatically generate when you create it based on the title. Just specify the page path like so: /my-page-permalink/'                        
- name: 'home'
  label: 'Home Page'
  create: false
  editor:
    preview: false
  files:
    - label: 'Home Page'
      name: 'home'
      file: '_pages/home.html'
      fields:
        - name: 'hero'
          label: 'Hero Section'
          hint: 'The section at the top of the page with the welcome message and the image slider'
          widget: 'object'
          collapsed: true
          fields:
          - name: 'title'
            label: 'Title'
            widget: 'string'
            hint: 'The title text at the top of the hero section'
          - name: 'text'
            label: 'Text'
            widget: 'textarea'
            hint: 'The text below the title of the hero section'
          - name: 'cta'
            label: 'Call to Action'
            widget: 'object'
            hint: 'The text link below the text of the hero section'
            fields: 
            - name: 'text'
              label: 'Text'
              widget: 'string'
            - name: 'link'
              label: 'Link'
              widget: 'string'
          - name: 'images'
            label: 'Image slider'
            hint: 'The image slider in the hero section. Add slides by clicking [button]'
            widget: 'list'
            collapsed: true
            fields: 
            - name: 'src'
              label: 'Image'
              widget: 'image'
            - name: 'alt'
              label: 'Image description (alt) text'
              hint: 'Description or alt text is a way to describe an image to screen readers for people with disabilities. This is required by the ADA and will help your search ranking.'
              widget: 'string'
            - name: 'text'
              label: 'Text'
              hint: 'The text that appears in the purple box in the bottom-right corner of the slide.'  
        - name: 'about'
          label: 'About Section'
          hint: 'The section below the hero where you talk about yourself.'
          widget: 'object'
          collapsed: true
          fields:
          - name: 'title'
            label: 'Title'
            hint: 'Title text of the about section'
            widget: 'string' 
          - name: 'text'
            label: 'Text'
            hint: 'Text for the about section'
            widget: 'textarea'
          - name: 'image'
            label: 'Image' 
            hint: 'Image for the about section. Alt text already configured as "headshot of Nancy Brodovsky".'  
          - name: 'cta'
            label: 'Call to Action'
            hint: 'Link text at the bottom of the about section'  
            widget: 'object'
            fields:
            - name: 'text'
              label: 'Text'
              hint: 'Link text. No need to add the arrows, they are automatically generated.'
              widget: 'string'
            - name: 'link'
              label: 'Link'
              hint: 'Link URL'
              widget: 'string'
        - name: 'news'
          label: 'News section'
          hint: "Add links to media you're featured in here"
          widget: 'object'
          collapsed: true
          fields: 
          - name: 'title'
            label: "Title"
            hint: 'The title text that appears at the top of the page'
            widget: 'string'
          - name: 'articles'
            label: 'Media'
            hint: 'Add a new link to media or edit existing links here'
            widget: 'list'
            fields: 
            - name: 'title'
              label: 'Title'
              widget: 'string'
              hint: 'Title of the media'
            - name: 'outlet'
              label: 'Outlet'
              hint: 'Press outlet of the media'
              widget: 'string'
            - name: 'link'
              label: 'Link'
              widget: 'string'
              hint: 'Link to the media. Link will be applied to the media title'       
        - name: 'reviews'
          label: 'Reviews section'
          hint: 'Add featured reviews from your clients here'
          widget: 'object'
          collapsed: true
          fields: 
          - name: 'title'
            label: 'Review section title'
            widget: 'string'
          - name: 'list'
            label: 'Reviews list'
            hint: 'Add or delete reviews here. Just select which client you want and order however you wish and the review excerpt or the first sentence of the review will appear on the homepage.'
            widget: 'list'
            fields:
            - name: 'client'
              label: 'Client'
              collection: 'clients'
              search_fields: ["title"]
              display_fields: ["title"]
              value_field: "{{slug}}"
              widget: 'relation'
        - name: 'clients'
          label: 'Clients section'
          hint: 'This section automatically feeds in all the clients you have added in alphabetical order. All you need to so here is update a title.'
          widget: 'object'
          collapsed: true
          fields:
          - name: 'title'
            label: 'Client section title'
            widget: 'string'
                
                  

                


               

        


              
              





        
